services:
  - type: web
    name: xstn-backend
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn xstn_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: xstn-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "xstn-backend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://xstn-backend.onrender.com"

databases:
  - name: xstn-db
    databaseName: xstndb
    user: xstnuser
