# Generated by Django 6.0.2 on 2026-03-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_contactform_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inquiryform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='position',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='joinapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='joinapplication',
            name='role',
        ),
        migrations.AddField(
            model_name='inquiryform',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='university',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinapplication',
            name='role_interested',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinapplication',
            name='why_join',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
