# Generated by Django 6.0.2 on 2026-02-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage_internshipapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
