# Generated by Django 6.0.2 on 2026-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_internshipapplication_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
